version: "3.1"

services:
    mysql:
        image: mysql:5.6
        container_name: my_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        # networks:
        #     - test_network_1
    admin:
        image: adminer:latest
        container_name: admin
        depends_on:
            - mysql
        ports:
            - 8088:8080
        # networks:
        #     - test_network_1
        #     - test_network_2

# networks:
    # To connect to an external network
    # default:
    #     external:
    #         name: external_network_name

    # test_network_1:
    #     driver: bridge # default

    # test_network_2:
    #     driver: bridge # default
