version: "3.1"

services:
    mysql:
        image: mysql:5.6
        container_name: my_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
    admin:
        image: adminer:latest
        container_name: admin
        depends_on:
            - mysql
        ports:
            - 8088:8080
